# Generated by Django 4.1.3 on 2022-12-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_annonce_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='semester',
            field=models.CharField(choices=[('neuf jamais utilise', 'Neuf jamais utilisé'), ('neuf', 'Neuf'), ('bon', 'Bon')], default='neuf_jamais_utilise', max_length=20),
        ),
    ]
